name: Build and Deploy to Render

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies and Quasar CLI
        run: |
          npm install -g @quasar/cli
          npm install

      - name: Build Quasar App
        run: quasar build

      - name: Trigger Render Deploy Hook
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST "$DEPLOY_HOOK"
